Add missing awaits to save method.
Refty/bubble-client pull request #4
Opened 2022-06-15 14:45 UTC by junjaytan

Otherwise running the async thing.save method does not work.

Add readme example about running search.

2022-06-15 15:00 UTC, ramnes requested changes
Awesome, thank you for being the first contributor! 🎉 

LGTM overall, only blocker for me is the README.

2022-06-15 15:00 UTC, ramnes commented on README.md
> +
Nice! Can you just put that block before "Join stuff!" so that the "Also works on cursors!" still makes sense? :)

2022-06-15 15:00 UTC, ramnes commented on README.md
> +>>> pet = await Pet.get_one(id=None, constraints=constraints)
Let's make it as simple as possible:
```suggestion
>>> pet = await Pet.get_one(constraints=constraints)
```

2022-06-15 15:00 UTC, ramnes commented on bubble_client.py
> +        return await self.post(**params)
Good catch! That being said, how did you encounter a problem with that? As is, `save` will still return a coroutine that will end up being awaited in user's code anyway so how can that cause any problem with the method?

2022-06-15 15:00 UTC, ramnes commented on setup.py
> +    python_requires=">=3.9, <4",
Good catch as well! Maybe we could keep a bit of backward compatibility by removing the dict merge operator instead? Both work for me, as you wish.

2022-06-15 16:47 UTC, junjaytan reviewed
Thanks for this client. It's saving me some time from having to write my own!

2022-06-15 16:47 UTC, junjaytan commented on README.md
> +>>> pet = await Pet.get_one(id=None, constraints=constraints)
Ah good catch. Done.

2022-06-15 16:47 UTC, junjaytan commented on README.md
> +
Sure, I obviously didn't read the cursors section too closely to realize it directly related to the join section ;-)

2022-06-15 16:47 UTC, junjaytan commented on setup.py
> +    python_requires=">=3.9, <4",
That sounds good. Reverted change to `setup.py`, using the less attractive dict unpacking syntax per https://peps.python.org/pep-0584/#d1-d2 that is supported for 3.5+.

2022-06-15 16:47 UTC, junjaytan commented on bubble_client.py
> +        return await self.post(**params)
As a caveat, I'm still new to Python async, but my understanding is that the method must still declare await for any async methods it's calling.

Here's a specific example: if I create a Pet object in my bubble store with two fields (name, org_id), then try to run a save (Put) with this simple script:

```
import asyncio
from bubble_client import BubbleThing, configure

class Pet(BubbleThing):
    pass

async def main(api_token):
    configure(base_url='MY_APP_BASE_URL',
              token=api_token)
    new = Pet(name_text='Mr Hyde.', org_id_number=2)
    await new.save()

if __name__ == '__main__':
    with open('bubble_token', 'r') as f:
        api_token = f.read()
    asyncio.run(main(api_token))
```

I get the following error:
```
run2.py:14: RuntimeWarning: coroutine 'BubbleThing.post' was never awaited
  await new.save()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

In contrast, running count succeeds per your readme:
```
count = await Pet.count()
print(count)
```

and if I add the await statements per this PR, the save also works.

Is there something I'm doing wrong in my call?

2022-06-15 16:51 UTC, junjaytan commented
Another quick question: when this client is updated, what determines when PyPI gets updated with the latest build?

2022-06-17 14:36 UTC, ramnes approved these changes

2022-06-17 14:36 UTC, ramnes commented
Looking good, thanks!

2022-06-17 14:36 UTC, merged